### ISSUE TITLE
能否增加IUIViewLocator对Addressable资源管理系统的支持

### ISSUE THREAD

**Issue by ezergame** [vovgou/loxodon-framework#13]
能否增加IUIViewLocator对Addressable资源管理系统的支持

**Comment by cocowolf** [comment]
我不是写了一个从Resources中加载的实现么，你按我的实现自己写一个Addressable的啊，我提供接口就是让你自己去根据自己的需求来实现。

**Comment by ezergame** [comment]
那LuaBehaviour中的ScriptReference能否加上对Addressable的支持呢，这个因为要改成异步的方式，涉及的地方有点多，希望能加上对Addressable的支持，这对于用Addressable实现lua热更新非常有用，感激不尽

**Comment by cocowolf** [comment]
LuaBehaviour我也不能加Addressable的支持，Addressable是Unity的一个可选插件，我不能让框架强制依赖它，如果别人没有导入Addressable就会报错了。这种支持，你都可以自己做啊，可以用你自己写的LuaBehaviour。这个框架的实现你都可以自定义，它完全面向接口写的，接口你不要修改，但是所有的接口实现你都可以自定义。不需要非得用我写的。

**Comment by ezergame** [comment]
谢谢回复，现在确实是在自己写

**Comment by vovgou** [comment]
> 那LuaBehaviour中的ScriptReference能否加上对Addressable的支持呢，这个因为要改成异步的方式，涉及的地方有点多，希望能加上对Addressable的支持，这对于用Addressable实现lua热更新非常有用，感激不尽

最新版本2.0.1修改了ScriptReference，使用体验与AssetReference差不多，文件拖上去就行，可以替代AssetReference了，而且加载还是同步的
