### ISSUE TITLE
log4 插件导入会报错

### ISSUE THREAD

**Issue by wildfire2015** [vovgou/loxodon-framework#26]
log4 插件包安装后报错

Library\PackageCache\com.vovgou.loxodon-framework-log4net@2.3.0\Runtime\Log\Log4Net\Log4NetLogImpl.cs(7,25): error CS0433: The type 'ILog' exists in both 'log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' and 'log4net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

一系列

删掉插件包Plugins里面的log4net.dll才不报错

**Comment by vovgou** [comment]
不要删我插件中的，把Unity官方的Plastic SCM 插件删掉
