### ISSUE TITLE
Related to enter play mode settings

### ISSUE THREAD

**Issue by ApprenticeGC** [vovgou/loxodon-framework#27]
Check "Enter Play Mode Settings" with no Reload domain will result error. Is there any setting necessary to be adjusted?
This is the doc from Unity, [Configurable Enter Play Mode](https://docs.unity3d.com/Manual/ConfigurableEnterPlayMode.html).
The errors I receive are

ArgumentException: An item with the same key has already been added.

DuplicateRegisterServiceException: Duplicate key IBinder
Loxodon.Framework.Services.ServiceContainer.Register[T]

I guess it is the use of static variable causing such errors? I am just wonering if there is a way to work with Loxodon framework as nowadays, turning on Enter Player Mode Settings speed up the development.

**Comment by vovgou** [comment]
I don't understand what your problem is

**Comment by vovgou** [comment]
> 
Please check your code, this error should be registering IBinder to the service container multiple times.

**Comment by vovgou** [comment]
[Loxodon.Framework2.4.2.zip](https://github.com/vovgou/loxodon-framework/files/9111812/Loxodon.Framework2.4.2.zip)

@ApprenticeGC   I modified the code to be compatible with the “Configurable Enter Play Mode” feature, please download the attachment

**Comment by ApprenticeGC** [comment]
Thanks for the modification. Everything works as expected after replacing with version 2.4.2.

**Comment by ApprenticeGC** [comment]
Hello Clark,

This is a general question which I don't think firing issues on GitHub will
be a good idea. Basically, I see that Loxodon has a message system(publish,
subscribe). I am just curious, is there any benchmark I can reference so
that I could understand how it compares to, signal bus of Zenject, UniRx
subject, C# event?

Regards
Ray

**Comment by vovgou** [comment]
> 
It's an alternative to C# event.
