### ISSUE TITLE
Git tag v2.4.5 is not aligned with the version update commit

### ISSUE THREAD

**Issue by favoyang** [vovgou/loxodon-framework#28]
v2.4.5 is created on Aug 15

![image](https://user-images.githubusercontent.com/125390/187144957-c6225cf8-c60d-42e5-b9a5-962c2490ab78.png)

But the actual version update commit is created on Aug 29

![image](https://user-images.githubusercontent.com/125390/187145072-08b63b81-b9e7-4ba1-aeec-a53fa0dc426f.png)

Please [re-tag](https://michaelheap.com/retag-git-tag/) 02e1ad0 as v2.4.5. So it can be processed by OpenUPM.

**Comment by vovgou** [comment]
Thank you！now i have fixed it.
