### ISSUE TITLE
WindowManager 

### ISSUE THREAD

**Issue by fooliker** [vovgou/loxodon-framework#3]
WindowManager.Clear()
不能将当前容器下面的所有Window销毁
  public virtual void Clear()
        {
            for (int i = this.windows.Count; i > 0; i--)
            {
                ### this.windows[0].Dismiss(true);### issue
            }
            this.windows.Clear();
        }

**Comment by cocowolf** [comment]
已修复

**Comment by giangnb-dev** [comment]
@cocowolf Instead of calling Dismiss() to destroy the window, I want to use the Hide() function to hide the window and reuse. Give me a solution, thank

**Comment by giangnb-dev** [comment]
And explain to me if I use Loadwindow and Dismiss to display the popup and close the popup ( Instantiate and Destroy ), does the large number of popups affect the performance of the game?

**Comment by cocowolf** [comment]
> @cocowolf Instead of calling Dismiss() to destroy the window, I want to use the Hide() function to hide the window and reuse. Give me a solution, thank

You can use the window.Hide() to hide the window.you can also dismiss the window, but keep WindowViewMode to restore the window state,or you cache the prefab of the view in the IUIViewLocator, so you can also quickly create a window.

**Comment by cocowolf** [comment]
> And explain to me if I use Loadwindow and Dismiss to display the popup and close the popup ( Instantiate and Destroy ), does the large number of popups affect the performance of the game?

If you cache the prefab of the window,so don't worry about this.
