### ISSUE TITLE
Service container doesn't register generics properly

### ISSUE THREAD

**Issue by kondratov-saritasa** [vovgou/loxodon-framework#30]
Steps to reproduce:
1. Create a generic service `Service<T>`
2. Register `Service<Type1>`
3. Register `Service<Type2>`

Result: `DuplicateRegisterServiceException` is thrown.

Expected: All works fine.

Here is a source of the problem: https://github.com/vovgou/loxodon-framework/blob/master/Loxodon.Framework/Assets/LoxodonFramework/Runtime/Framework/Services/ServiceContainer.cs#L72

```
namespace Loxodon.Framework.Services
{
    public class ServiceContainer : IServiceContainer, IDisposable
    {
        private Dictionary<string, IFactory> services = new Dictionary<string, IFactory>();

        public virtual object Resolve(Type type)
        {
            return this.Resolve<object>(type.Name);
        }

        public virtual T Resolve<T>()
        {
            return this.Resolve<T>(typeof(T).Name);
        }

...

        public virtual void Register<T>(T target)
        {
            this.Register<T>(typeof(T).Name, target);
        }
```

`typeof(T).Name` for `Service<Type1>`  `Service<Type2>` will return same string: `Service'1`. 

My suggestion is to use `typeof(T).ToString()` then we get something like: `Service'1[Type1]` and `Service'1[Type2]`. If you ok with that - I can prepare a PR.

**Comment by vovgou** [comment]
I need to think about your suggestion,because changing it may break existing code.

In the question you mentioned, you can inherit the IServiceContainer interface and customize your own ServiceContainer，even you can integrate Zenject, a more powerful IoC/DI container.

**Comment by kondratov-saritasa** [comment]
@vovgou That is what I did already. But I decided to report in hope it might be resolved sometime. 

Regarding breaking something - I think this unlikely will happen unless you save registered services somewhere (like serialize to file) or may be lookup for services manually.

Also as an option we could have different strategy for generic classes and keep current code for usual classes.

**Comment by vovgou** [comment]
> @vovgou That is what I did already. But I decided to report in hope it might be resolved sometime.
> 
> Regarding breaking something - I think this unlikely will happen unless you save registered services somewhere (like serialize to file) or may be lookup for services manually.
> 
> Also as an option we could have different strategy for generic classes and keep current code for usual classes.

I'll change it and release it in the next version.
![image](https://user-images.githubusercontent.com/2171221/194695083-0219697a-54c4-40bb-8085-b34f17e080c4.png)

**Comment by vovgou** [comment]
> 

I will modify it in the next version.
![image](https://user-images.githubusercontent.com/2171221/194701279-a9c4e305-9463-4293-b36c-b07a22893260.png)
