### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by AsheshPlays** [vovgou/loxodon-framework#32]
Does this provide assetbundle encryption ?And what is the difference of this framework from the one on unity store? It seems they are different versions.

Edit: Sorry I was referring to the Bundle Maker. Well, my question for thr bundle is, can it create encryption where my asset cant be opened by ripping?

**Comment by vovgou** [comment]
Loxodon.Framework.Bundle is a plugin for this framework.It supports encrypting Unity's asset bundle, but it will slow down the loading speed of assets, so I only recommend using it to encrypt some sensitive assets.It can only increase the difficulty of cracking assets, and cannot ensure that your assets are absolutely safe.

**Comment by AsheshPlays** [comment]
So is it better to just use assetbundle with no encryption? but can i use obfuscator instead for code protection ?

**Comment by vovgou** [comment]
I suggest that the art resources in the game should not be encrypted.Only json, xml or SQLite related to the core logic of the game needs to be encrypted.
Of course you can use obfuscators, it can also increase the difficulty of cracking.

In fact, Unity's AssetBundle itself has certain anti-cracking capabilities.Without the original Unity project, it is difficult for you to modify the AssetBundle and republished it.
