### ISSUE TITLE
[Feature] Split the framework further

### ISSUE THREAD

**Issue by ApprenticeGC** [vovgou/loxodon-framework#35]
Thanks to provide such a wonderful package for making mvvm work flawlessly in Unity. After adjusting the current project, I find out that the use of Microsoft.Extension.Logging for logging and Message Pipe for message publishing/subscribing will be more suitable. I am just wondering if the core part of the framework can be further split so that the logging, messaging etc. could be extracted. Or providing a way to replace them with other solution maybe?

**Comment by vovgou** [comment]
Please reimplement the ILogFactory interface to support Microsoft.Extension.Logging.
![image](https://github.com/vovgou/loxodon-framework/assets/2171221/c91daeb1-ca6a-4c29-83cc-fa787842cd39)

About the Messaging system, this is an optional module, you can integrate any messaging system you like into my framework.
