### ISSUE TITLE
请教一下使用ResourcesViewLocator加载的资产什么时候释放呢

### ISSUE THREAD

**Issue by ericzhanchina** [vovgou/loxodon-framework#37]
请教一下使用ResourcesViewLocator加载的资产什么时候释放呢，如果使用了XAsset异步加载了资产，不需要主动调用release吗？

**Comment by vovgou** [comment]
根据IUIViewLocator的接口，自定义一个XAssetViewLocator的实现，通过XAsset加载Window或者View，实例化后，可以自己挂载一个管理生命周期的脚本，在这个脚本的OnDestroy函数中调用XAsset的Release函数释放即可。
