### ISSUE TITLE
在FormattableTextMeshProUGUI & TemplateTextMeshProUGUI中Text.text会被自身的OnEnable设置为初始值

### ISSUE THREAD

**Issue by FirmianaMarsili** [vovgou/loxodon-framework#38]
源代码：
``` c#
        protected override void OnEnable()
        {
            base.OnEnable();
            Initialize();
        }

        public override void SetAllDirty()
        {
            base.SetAllDirty();
            Initialize();
        }

        protected virtual void Initialize()
        {
            SetText(BUFFER.Clear().Append(m_Template));//格式化为默认值
        }
```

重现步骤：

1. 将任意Template or Formattable绑定数据模型
2. 在Text激活状态下更新数据
3. 将Text的状态关闭并再次激活
4. 此时`Text.text`会被`Initialize`设置为`Text.Format`

**Comment by vovgou** [comment]
好的，我改一下

**Comment by FirmianaMarsili** [comment]
```c#
        GenericParameters<int, int,string> example;

        ViewModel = new FormattableViewModel();
        BindingSet<FormattableView, FormattableViewModel> bindingSet = this.CreateBindingSet(ViewModel);
        bindingSet.Bind(Example).For(v => v.Parameter1).To(vm => vm.Month);
        bindingSet.Bind(Example).For(v => v.Parameter2).To(vm => vm.Day);
        bindingSet.Bind(Example).For(v => v.Parameter3).To(vm => vm.Hour);


        protected internal override void OnParameterChanged()
        {
            try
            {
                if (m_Text == null || !m_Text.enabled)
                    return;

                m_Text.SetText(BUFFER.Clear().AppendFormat<P1, P2, P3>(m_Text.Format, parameter1, parameter2, Parameter3));
            }
            catch (Exception e)
            {
#if DEBUG
                if (Application.isEditor)
                    Debug.LogWarning(e);
#endif
                m_Text.SetText(BUFFER.Clear().Append(m_Text.Format));
            }
        }
```

另外在上述示例中，当`GenericParameters`存在引用类型时，在绑定`Parameter1`后更新视图会因为`string`为`null`导致`AppendFormat`失败。在我两个版本的unity，`2021.3.7f1`和`2022.3.14f1`中测试一个表现为长时间卡顿，一个崩溃。需要避免混用，或者可以先绑定`Parameter3`

**Comment by vovgou** [comment]
> ```cs
>         GenericParameters<int, int,string> example;
> 
>         ViewModel = new FormattableViewModel();
>         BindingSet<FormattableView, FormattableViewModel> bindingSet = this.CreateBindingSet(ViewModel);
>         bindingSet.Bind(Example).For(v => v.Parameter1).To(vm => vm.Month);
>         bindingSet.Bind(Example).For(v => v.Parameter2).To(vm => vm.Day);
>         bindingSet.Bind(Example).For(v => v.Parameter3).To(vm => vm.Hour);
> 
> 
>         protected internal override void OnParameterChanged()
>         {
>             try
>             {
>                 if (m_Text == null || !m_Text.enabled)
>                     return;
> 
>                 m_Text.SetText(BUFFER.Clear().AppendFormat<P1, P2, P3>(m_Text.Format, parameter1, parameter2, Parameter3));
>             }
>             catch (Exception e)
>             {
> #if DEBUG
>                 if (Application.isEditor)
>                     Debug.LogWarning(e);
> #endif
>                 m_Text.SetText(BUFFER.Clear().Append(m_Text.Format));
>             }
>         }
> ```
> 
> 另外在上述示例中，当`GenericParameters`存在引用类型时，在绑定`Parameter1`后更新视图会因为`string`为`null`导致`AppendFormat`失败。在我两个版本的unity，`2021.3.7f1`和`2022.3.14f1`中测试一个表现为长时间卡顿，一个崩溃。需要避免混用，或者可以先绑定`Parameter3`

没理解什么意思，描述清楚一点。

**Comment by vovgou** [comment]
> ```cs
>         GenericParameters<int, int,string> example;
> 
>         ViewModel = new FormattableViewModel();
>         BindingSet<FormattableView, FormattableViewModel> bindingSet = this.CreateBindingSet(ViewModel);
>         bindingSet.Bind(Example).For(v => v.Parameter1).To(vm => vm.Month);
>         bindingSet.Bind(Example).For(v => v.Parameter2).To(vm => vm.Day);
>         bindingSet.Bind(Example).For(v => v.Parameter3).To(vm => vm.Hour);
> 
> 
>         protected internal override void OnParameterChanged()
>         {
>             try
>             {
>                 if (m_Text == null || !m_Text.enabled)
>                     return;
> 
>                 m_Text.SetText(BUFFER.Clear().AppendFormat<P1, P2, P3>(m_Text.Format, parameter1, parameter2, Parameter3));
>             }
>             catch (Exception e)
>             {
> #if DEBUG
>                 if (Application.isEditor)
>                     Debug.LogWarning(e);
> #endif
>                 m_Text.SetText(BUFFER.Clear().Append(m_Text.Format));
>             }
>         }
> ```
> 
> 另外在上述示例中，当`GenericParameters`存在引用类型时，在绑定`Parameter1`后更新视图会因为`string`为`null`导致`AppendFormat`失败。在我两个版本的unity，`2021.3.7f1`和`2022.3.14f1`中测试一个表现为长时间卡顿，一个崩溃。需要避免混用，或者可以先绑定`Parameter3`

真是一个奇怪的bug，下面的代码，第一次点击Unity的Play运行时，正确调用 Format(ReadOnlySpan<char> format,object value, StringBuilder builder)这个函数，但是第二次点击Play，则调用的是 void Format(string format, object value, StringBuilder builder)函数，所以崩溃了。

 IFormatter formatter = IFormatter.GetFormatter<string>();
 ReadOnlySpan<char> format = new ReadOnlySpan<char>(new char[] { 'a' });
 formatter.Format(format, null, builder);

**Comment by vovgou** [comment]
使用这2个包吧，修复了

没别的办法，暂时将重载函数void Format(string format, object value, StringBuilder builder)注释掉了，避免调用紊乱

![image](https://github.com/vovgou/loxodon-framework/assets/2171221/63ae613f-87a8-4e65-b2b3-b81d94ae6127)
