### ISSUE TITLE
InteractionTargetProxy的Target被意外释放

### ISSUE THREAD

**Issue by ChaosVan** [vovgou/loxodon-framework#39]
TargetProxyBase中的target是一个WeakReference，target是LuaTable的时候，有时会意外变成null。业务那边是将一个View中异步的InteractionAction和VM中异步的InteractionRequest做绑定
```lua
bindingSet:Bind(self):For("gameAlertAsyncInteractionAction"):To("testAsyncInteractionRequest")
```
```lua
function M:TestInteractionRequest()
    self.testCommand.Enabled = false
    Executors.RunLuaOnCoroutineNoReturn(async(function()
        local notification = GameAlertNotification("未知事件", "事件类型未知", "确定")
        await(self.testAsyncInteractionRequest:Raise(notification))
        self.testCommand.Enabled = true
        log.debug(notification.DialogResult)
    end))
end
```
![image](https://github.com/vovgou/loxodon-framework/assets/1716237/5e785dd3-920d-40e0-8ffc-e3e39ebcc638)
![image](https://github.com/vovgou/loxodon-framework/assets/1716237/7905a222-26ea-4b78-b7fc-059b5ca4fe93)

请大神帮忙看看问题~感谢

**Comment by vovgou** [comment]
以前SimpleCommand有同样的问题，所有SimpleCommand构造函数有一个参数keepStrongRef可以确保是强引用类型。但是你这里的Target，应该是一个视图界面上的对象（UGUI控件、Window或者View对象），如果视图界面存在，就不应该被释放。为啥它会是一个lua的表呢？我觉得你这用法有点问题。

**Comment by ChaosVan** [comment]
target是Lua那边的一个View对象，也就是下面绑定代码中的self，gameAlertAsyncInteractionAction是一个AsyncLoadableInteractionActionBase<object>对象，testAsyncInteractionRequest是一个AsyncInteractionRequest<GameAlertNotification> 对象。
```lua
bindingSet:Bind(self):For("gameAlertAsyncInteractionAction"):To("testAsyncInteractionRequest")
```

另外，如果我将InteractionAction和InteractionRequest都换成同步的，将UIPrefab放在Resources中，就不会出现target为空的情况（关于这点我还在继续测试），我再多尝试几种绑定方式看看。

**Comment by ChaosVan** [comment]
好像破案了...Bind的时候，不加那个self就好了，CreateBindingSet的时候创建的LuaBindingSet里的target是C#的对象
```lua
bindingSet:Bind():For("gameAlertAsyncInteractionAction"):To("testAsyncInteractionRequest")
```
感谢大神解惑~

**Comment by vovgou** [comment]
好的，解决了就好，有问题在QQ群里面问我吧，沟通起来比较快！
622321589
