### ISSUE TITLE
trampolines compile how-to?

### ISSUE THREAD

**Issue by ghost** [vovgou/loxodon-framework#4]
Hi, I own your bundle product on unity asset store. I am trying to find out more info about AOT Trampolines on iOS. I found this link below:
https://www.mono-project.com/docs/advanced/runtime/docs/trampolines/

- however I do not know the specifics of how it relates to your project or how to use this feature. Where do I paste your AOT Compilation Option?
xcode? xamarin?

Can I paste only one option or all? 
i.e. are they referring to standard, PLT, delegate?

I believe I understand what they do. It is the only way to use runtime code on iOS - as the iOS platform doesn't support JIT. I assume this lets us use xlua on iOS. My limited understanding is that on AOT we get a token for the type/ptl/delegate we are accessing so we can call the method from xlua in a more static  and likely secure way?
 

Mainly just a hello world for iOS and AOT using these trampolines and where to put those compilation options and what each does, is all we would need.

Thank you for your time reading this.
also mentioned on unity forums, not sure which would get your eyes first :-)
https://forum.unity.com/threads/loxodon-framework-mvvm.545335/#post-4849013

**Comment by cocowolf** [comment]
Hi

The configuration of trampolines is not necessary now, but in the early versions of Unity3d,if not configured, it will cause the game to crash on the iOS platform.

Please read the following article:
https://forum.unity.com/threads/trampolines-which-is-for-what.342739/

Please configure them in the location shown below.
![](https://user-images.githubusercontent.com/2171221/62909762-8da7f800-bdb0-11e9-947c-50c58eb350f3.png)
