### ISSUE TITLE
Loxodon.Framework.Views.TextMeshPro.GenericParameters在绑定引用类型时有概率崩溃

### ISSUE THREAD

**Issue by FirmianaMarsili** [vovgou/loxodon-framework#43]
## 问题描述：
在视图中对GenericParameters进行绑定时，会因为访问引用类型时为空而导致unity出现崩溃
## 复现过程：
末尾附件有一个简单的demo，或者声名任意一个`GenericParameters<p1, p2, etc.>`只需要泛型中包含任意引用类型即可。
## 当前的行为：
点击运行demo进行绑定视图，有大概率会直接崩溃。
## 期待的行为：
1.视图绑定时不会因为空值而崩溃
2.`FormattableTextMeshProUGUI`中对于`m_Format`字段添加`TextArea`标签
3.对于`FormattableTextMeshProUGUI`类型添加一个右键菜单`MenuItem("GameObject/UI/Text - FormattableTextMeshProUGUI")`
## 屏幕截图（这个是Demo的调用堆栈）：
![crash](https://github.com/vovgou/loxodon-framework/assets/35676922/f9c6eb49-1b39-4515-9e53-d9562ab3edde)
## 环境：
Windows 10 22H2
Unity 2021.3.14f1
## Demo：
[2021_3_a.zip](https://github.com/user-attachments/files/15747395/2021_3_a.zip)

**Comment by vovgou** [comment]
这个版本不应该有这个崩溃的问题啊。我使用你的demo测试也没有发生崩溃。以前确实有这个崩溃，原因见下图英文描述。

在UnityEditor中，当参数类型为ReadOnlySpan<char>时，第一次调用是正确的，第二次调用时，实际调用的是void Format(string format, object value, StringBuilder builder)函数，这样会导致UnityEditor崩溃。

![image](https://github.com/vovgou/loxodon-framework/assets/2171221/9ba31f73-e78e-4b8e-b86c-9d7a2fc7ca83)
