### ISSUE TITLE
 framework/AsyncInteractionRequest.lua:1: unexpected symbol near '<\239>'

### ISSUE THREAD

**Issue by zhongjunhang** [vovgou/loxodon-framework#46]
运行Xlua Example出现 framework/AsyncInteractionRequest.lua:1: unexpected symbol near '<\239>',经排查由于AsyncInteractionRequest.lua.txt保存为UTF-8 with BOM导致，保存为UTF-8解决问题

**Comment by vovgou** [comment]
> 运行Xlua Example出现 framework/AsyncInteractionRequest.lua:1: unexpected symbol near '<\239>',经排查由于AsyncInteractionRequest.lua.txt保存为UTF-8 with BOM导致，保存为UTF-8解决问题

是的，已经发现了，下个版本我会修复。你另存一下，改成UTF8
