### ISSUE TITLE
Fody.MethodDecorator

### ISSUE THREAD

**Issue by Alex1234x** [vovgou/loxodon-framework#47]
Thank you very much for modifying the fody library to work with unity.

I really want to use [MethodDecorator](https://github.com/Fody/MethodDecorator) but I can’t figure out how and what needs to be changed in this library to make it work with your version of fody and how to connect it to the Unity project. Can you advise and help?

Thank you very much!!!
With best regards.

**Comment by vovgou** [comment]
> Thank you very much for modifying the fody library to work with unity.
> 
> I really want to use [MethodDecorator](https://github.com/Fody/MethodDecorator) but I can’t figure out how and what needs to be changed in this library to make it work with your version of fody and how to connect it to the Unity project. Can you advise and help?
> 
> Thank you very much!!! With best regards.

You don't need to modify any code. Simply download the MethodDecorator DLL library (.net standard 2.0 or .net standard 2.1) from NuGet and package it as a UPM plugin. You can refer to my example Loxodon.Framework.Fody.ToString.

![image](https://github.com/user-attachments/assets/1fffb328-8318-4a3f-b7b8-b6611f6480b1)
![image](https://github.com/user-attachments/assets/c422ce93-c826-4b8d-b242-7f612482048a)
![image](https://github.com/user-attachments/assets/bb3e3121-10c2-4d9b-b22d-7b88ed20b73f)

**Comment by Alex1234x** [comment]
Hello

Hello.
Thank you for your response and participation. But unfortunately for me,
what you describe as simple and obvious actions is completely
incomprehensible. I do not understand the project storage structure in
UNITY and only understand in general terms that a DLL can be linked to a
project. I don’t quite understand what and where to copy from. It is
possible to install the library via NuGet for Unity - but apparently this
is not what you are writing about. You can also download the dll file
itself from the site, and I can also download your library and still don’t
understand what and where to copy in the end.

[image: изображение.png]
[image: изображение.png]
[image: изображение.png]

Help me please


пн, 22 июл. 2024 г. в 08:25, Clark Yang ***@***.***>:

**Comment by Alex1234x** [comment]
Hello.
Thank you for your response and participation. But unfortunately for me,
what you describe as simple and obvious actions is completely
incomprehensible. I do not understand the project storage structure in
UNITY and only understand in general terms that a DLL can be linked to a
project. I don’t quite understand what and where to copy from. It is
possible to install the library via NuGet for Unity - but apparently this
is not what you are writing about. You can also download the dll file
itself from the site, and I can also download your library and still don’t
understand what and where to copy in the end.
![1-NuGetForUnity](https://github.com/user-attachments/assets/5e040c4e-cb53-44fb-aa3f-f5e085e484db)
![2-MethodDecorator](https://github.com/user-attachments/assets/e88a5f1c-9ea7-4e80-a954-07b68e400a33)
![3-LoxodonFramework](https://github.com/user-attachments/assets/6c63646d-4bc8-49ca-8233-981b2f3cee5b)

**Comment by vovgou** [comment]
Yes, just download these DLLs from nuget, then refer to my project and put them in the Packages directory of Unity.

https://github.com/vovgou/loxodon-framework/tree/master/Loxodon.Framework.Fody/Packages/com.vovgou.loxodon-framework-fody-tostring

**Comment by Alex1234x** [comment]
Good afternoon.
I’m very sorry for my stupidity, but I can’t figure out this probably not complicated, but incomprehensible process for me.

I copied the files from your project and added the description from your project's manifest.json file to an empty new project. Now the folder structure of the project is completely empty and files have been added.

```
\Packages                                                                                                                                                                                                                                     
<DIR>	com.vovgou.loxodon-framework-fody
<DIR>	com.vovgou.loxodon-framework-fody-bindingproxy
<DIR>	com.vovgou.loxodon-framework-fody-propertychanged
<DIR>	com.vovgou.loxodon-framework-fody-tostring
	manifest.json
```

```
\Assets\LoxodonFramework\Editor\AppData
<DIR>	Fody
	Fody.meta
```

I want the MethodDecorator to work, for this I need to copy it somewhere and connect it somehow, like how I need to create and fill in FodyWeavers.xml
I don't understand what exactly and where to copy from https://github.com/Fody/MethodDecorator/tree/master
Please be so kind as to tell us in detail.

![Loxodon Framework Fody1](https://github.com/user-attachments/assets/9e9d472c-dd11-4da1-8799-7aa8c2e479f2)
![Loxodon Framework Fody2](https://github.com/user-attachments/assets/47bfe7dd-0ad7-4746-b954-61893394a45e)
![Loxodon Framework Fody3](https://github.com/user-attachments/assets/68735c21-80a2-4d38-a33c-2e26d3c93a8e)
