### ISSUE TITLE
基于数据绑定方式做动效方便吗？

### ISSUE THREAD

**Issue by Drecik** [vovgou/loxodon-framework#52]
数据绑定了之后做动效方便吗？
比如头顶上的金币栏，绑定的model层的金币从10变成了20，需要播放金币飞入，数字变化动画
比如任务完成之后，任务列表里面需要播放任务完成及删除动画（或者刷新动画）

这种情况下怎么做比较好？

**Comment by vovgou** [comment]
你这属于视图控件的逻辑，你做一个数字滚动动画的UI控件就好了（不做控件随便写个动画脚本也行），数据绑定后，一但金币值变化你的控件就会收到新的值，这时候你播放滚动动画就行。
