### ISSUE TITLE
绑定ScriptableObject的数据时产生Warning

### ISSUE THREAD

**Issue by Macyrate** [vovgou/loxodon-framework#53]
ScripatbleObject不是Observable的，但UI组件经常需要展示其中的数据，这会产生大量的如下Warning：

```
[WARN] PropertyNodeProxy - The type MyInfo does not inherit the INotifyPropertyChanged interface and does not support the PropertyChanged event.
```

**Comment by vovgou** [comment]
> ScripatbleObject不是Observable的，但UI组件经常需要展示其中的数据，这会产生大量的如下Warning：
> 
> ```
> [WARN] PropertyNodeProxy - The type MyInfo does not inherit the INotifyPropertyChanged interface and does not support the PropertyChanged event.
> ```

绑定的前提是VM对象必须是集成了 INotifyPropertyChanged 的对象。这是MVVM的规范，你为啥要绑ScripatbleObject？你先看下文档。

**Comment by vovgou** [comment]
这个警告就是提示你这么做的风险。如果符合你预期，你可以不用理这个警告。不过最好你保证VM标准化，不要用ScriptableObject这种东西
