### ISSUE TITLE
Binding enum failed

### ISSUE THREAD

**Issue by yanjingzhaisun** [vovgou/loxodon-framework#6]
# Issue
BindingSet.Bind().For(v=>v.enumType).To(vm=>vm.enumType) got error.

# How to reproduce
Step 1: Declare a public enum type, and a public enum property, for both view and view model class. Property in view model needs to follow the Set<> function inherited from ViewModelBase class.
Step 2: In View class, create a bindingSet, and bind the view's enum property onto viewModel's enum property.
Step 3: In controller class, set data context.
Step 4: Run the game

# Reasons
In Binding.cs, the enum type was cast as Int32.

**Comment by cocowolf** [comment]
Thank you for the report, it has been fixed！
